all:
	rustc functions.rs -o bin/functions
	rustc variables_values_types.rs -o bin/variables_values_types
	rustc logic_expressions.rs -o bin/logic_expressions
	rustc misc.rs -o bin/misc
	rustc iteration.rs -o bin/iteration
	rustc advanced_data_manipulation.rs -o bin/advanced_data_manipulation
	rustc classes_and_methods.rs -o bin/classes_and_methods

clean:
	rm -f bin/*
